CLASS LCL_BUSINESSPARTNER_CHANGED_V1 DEFINITION FINAL INHERITING FROM /IWXBE/CL_ABS_CONSUMER_EVENT.
  PUBLIC SECTION.
    INTERFACES:
      ZBPIF_BUSINESSPARTNER_CHA_57D7.

ENDCLASS.

CLASS LCL_BUSINESSPARTNER_CHANGED_V1 IMPLEMENTATION.
  METHOD ZBPIF_BUSINESSPARTNER_CHA_57D7~GET_BUSINESS_DATA.
      mo_event->get_business_data( IMPORTING es_business_data = rs_business_data ).
  ENDMETHOD.
ENDCLASS.
CLASS LCL_BUSINESSPARTNER_CREATED_V1 DEFINITION FINAL INHERITING FROM /IWXBE/CL_ABS_CONSUMER_EVENT.
  PUBLIC SECTION.
    INTERFACES:
      ZBPIF_BUSINESSPARTNER_CRE_A9A2.

ENDCLASS.

CLASS LCL_BUSINESSPARTNER_CREATED_V1 IMPLEMENTATION.
  METHOD ZBPIF_BUSINESSPARTNER_CRE_A9A2~GET_BUSINESS_DATA.
      mo_event->get_business_data( IMPORTING es_business_data = rs_business_data ).
  ENDMETHOD.
ENDCLASS.
