CLASS LCL_SALESCONTRACT_CHANGED_V1 DEFINITION FINAL INHERITING FROM /IWXBE/CL_ABS_CONSUMER_EVENT.
  PUBLIC SECTION.
    INTERFACES:
      ZDEVIF_SALESCONTRACT_CHAN_62F6.

ENDCLASS.

CLASS LCL_SALESCONTRACT_CHANGED_V1 IMPLEMENTATION.
  METHOD ZDEVIF_SALESCONTRACT_CHAN_62F6~GET_BUSINESS_DATA.
      mo_event->get_business_data( IMPORTING es_business_data = rs_business_data ).
  ENDMETHOD.
ENDCLASS.
CLASS LCL_SALESCONTRACT_CREATED_V1 DEFINITION FINAL INHERITING FROM /IWXBE/CL_ABS_CONSUMER_EVENT.
  PUBLIC SECTION.
    INTERFACES:
      ZDEVIF_SALESCONTRACT_CREA_5C3C.

ENDCLASS.

CLASS LCL_SALESCONTRACT_CREATED_V1 IMPLEMENTATION.
  METHOD ZDEVIF_SALESCONTRACT_CREA_5C3C~GET_BUSINESS_DATA.
      mo_event->get_business_data( IMPORTING es_business_data = rs_business_data ).
  ENDMETHOD.
ENDCLASS.
CLASS LCL_SALESCONTRACT_DELETED_V1 DEFINITION FINAL INHERITING FROM /IWXBE/CL_ABS_CONSUMER_EVENT.
  PUBLIC SECTION.
    INTERFACES:
      ZDEVIF_SALESCONTRACT_DELE_99DD.

ENDCLASS.

CLASS LCL_SALESCONTRACT_DELETED_V1 IMPLEMENTATION.
  METHOD ZDEVIF_SALESCONTRACT_DELE_99DD~GET_BUSINESS_DATA.
      mo_event->get_business_data( IMPORTING es_business_data = rs_business_data ).
  ENDMETHOD.
ENDCLASS.
CLASS LCL_SALESCONTRACT_ITEMCHA_1CF8 DEFINITION FINAL INHERITING FROM /IWXBE/CL_ABS_CONSUMER_EVENT.
  PUBLIC SECTION.
    INTERFACES:
      ZDEVIF_SALESCONTRACT_ITEM_7A98.

ENDCLASS.

CLASS LCL_SALESCONTRACT_ITEMCHA_1CF8 IMPLEMENTATION.
  METHOD ZDEVIF_SALESCONTRACT_ITEM_7A98~GET_BUSINESS_DATA.
      mo_event->get_business_data( IMPORTING es_business_data = rs_business_data ).
  ENDMETHOD.
ENDCLASS.
CLASS LCL_SALESCONTRACT_ITEMCRE_2C0B DEFINITION FINAL INHERITING FROM /IWXBE/CL_ABS_CONSUMER_EVENT.
  PUBLIC SECTION.
    INTERFACES:
      ZDEVIF_SALESCONTRACT_ITEM_43FD.

ENDCLASS.

CLASS LCL_SALESCONTRACT_ITEMCRE_2C0B IMPLEMENTATION.
  METHOD ZDEVIF_SALESCONTRACT_ITEM_43FD~GET_BUSINESS_DATA.
      mo_event->get_business_data( IMPORTING es_business_data = rs_business_data ).
  ENDMETHOD.
ENDCLASS.
CLASS LCL_SALESCONTRACT_ITEMDEL_F1F9 DEFINITION FINAL INHERITING FROM /IWXBE/CL_ABS_CONSUMER_EVENT.
  PUBLIC SECTION.
    INTERFACES:
      ZDEVIF_SALESCONTRACT_ITEM_27A1.

ENDCLASS.

CLASS LCL_SALESCONTRACT_ITEMDEL_F1F9 IMPLEMENTATION.
  METHOD ZDEVIF_SALESCONTRACT_ITEM_27A1~GET_BUSINESS_DATA.
      mo_event->get_business_data( IMPORTING es_business_data = rs_business_data ).
  ENDMETHOD.
ENDCLASS.
